# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: emerald
  font: "serif"

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'Anu Oluwatuyi personal website'
    twitter: 'anuoluwatuyi'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: right
    fixed_to_top: true
    highlight_active_link: true
    show_search: true
    show_theme_chooser: true
    showlogo: true
    logo:
      text: "Anu Oluwatuyi"
      # icon: icon.png

# Site footer
footer:
  copyright:
    notice: '© {year} Anu Oluwatuyi'
    license:
      enable: true
      allow_derivatives: true
      share_alike: true
      allow_commercial: true

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  search:
    provider: hugo-blox
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  avatar:
    gravatar: false
    shape: circle
  map:
    provider: mapnik
    api_key: ''
    zoom: 15
  math:
    enable: false
  privacy_pack:
    enable: false
